### ISSUE TITLE
Current ProCoDa situation

### ISSUE THREAD

**Issue by LeenaSen** [AguaClara/HRS-Flow-Recycle#10]
It seems like we need another login in order to access a drive we do not have for ProCoDa-- Justin looked into the situation some more and was not able to get it running on the computer on the side of the room that has the door to the grad lab. Would we be able to meet some time to get the rest of the login and software info to run ProCoDa? Thank you! @monroews 
![image](https://user-images.githubusercontent.com/43453124/53982125-1758e880-40e2-11e9-9d7d-26328b29f0d4.png)

**Comment by monroews** [comment]
Which computer is this? Is this in grad lab or the Fluoride gravity station?
@DesireeJSausele would need to follow the complete install as detailed at the [ProCoDA install page](https://github.com/monroews/LabVIEW/wiki/ProCoDA). You will need to complete the 4 steps.

**Comment by DesireeJSausele** [comment]
This is in the grad lab. I'll take a look at it!
